### ISSUE TITLE
Would you mind give one path for building one Fronted-end app?

### ISSUE THREAD

**Issue by Gnosnay** [JayZang/Twitter-Web-Like#2]
Hi Jay
I'm a novice for fronted-end app, but focus on the backend stuff. I am looking for one proper example to learn the best practice for building one website.
I searched the github and finally find this repo!
it is so awesome! I can find the modules that you have enclosed, which is so elegant.
I can find you put all requests under `./client/API`, all views and layout under `./client/View`, all static files under `./client/assets` and all reusable UI components under `./client/components`.

That's so great! it is clear to code and review. but there still are some details i dont know. would you mind give one way to learn it?

- why and how did you enclose the http request to `./client/API` and how to use them?
    i found that you use these code to login:
    ```javascript
    this.$store.dispatch('login', {
        account: this.account,
        password: this.password,
      })
      if (!res.result) {
        console.log(res)
        this.errHint = res.errMsg
        return
      }
      this.$router.push('/')
    }
    ```
    i have no idea about why do you use one string `login` to call the http request method. Would you mind telling me what tech it is? which doc do i need to read... :(

- what is `./client/store` and what is it used for?
    i think it is linked with last question 🤔I think it is related with `vuex` i will check it🤔 that is so confused...

I am so hopefully for you reply... thx a lot

**Comment by JayZang** [comment]
Hi @Yansongsongsong
I am very sorry about I am too late to notice this issue you created. Maybe you have found the answer, but I am still willing to reply your questions.  

- why and how did you enclose the http request to ./client/API and how to use them?
Because put all http requests into the indicated folder can let me easily manage and find the api what I want to call. To request to backend server, It simply import the module like this way `import personInfo from '@/API/Person/info'` and call the function that module have.
The above code you provided is one usage for vuex. You can visit the path `./client/store/modules/auth.js`. There is a action method called `login` and this method will call login API. And the one way to call actions method is  `this.$store.dispatch('ACTION_NAME', ObjectParameter)`. So the above code you provided will call the vuex action method instead directly call the function login which at `./client/API`.
```node
const action = {
  // Action method
  login: async ({commit}, para) => {
    if (!para.account || !para.password) {
      return {
        errMsg: '帳號和密碼請勿空白',
        result: false
      }
    }

    // Here will call the login API
    let {res, token} = await userAuth.login(para)

    if (res.result) {
      commit('setUser', res.user)
      commit('setAuthToken', token)
      commit('setLoginTime', moment())
      window.localStorage.setItem('AuthToken', token)
    }
    return res
  }
}
``` 
- Yap, it is related with vuex. It's is used to declare the entire web states and the method that can change the states. 

[Vuex Reference](https://vuex.vuejs.org/guide/)

**Comment by Gnosnay** [comment]
> Hi @Yansongsongsong
> I am very sorry about I am too late to notice this issue you created. Maybe you have found the answer, but I am still willing to reply your questions.
> 
> * why and how did you enclose the http request to ./client/API and how to use them?
>   Because put all http requests into the indicated folder can let me easily manage and find the api what I want to call. To request to backend server, It simply import the module like this way `import personInfo from '@/API/Person/info'` and call the function that module have.
>   The above code you provided is one usage for vuex. You can visit the path `./client/store/modules/auth.js`. There is a action method called `login` and this method will call login API. And the one way to call actions method is  `this.$store.dispatch('ACTION_NAME', ObjectParameter)`. So the above code you provided will call the vuex action method instead directly call the function login which at `./client/API`.
> 
> ```js
> const action = {
>   // Action method
>   login: async ({commit}, para) => {
>     if (!para.account || !para.password) {
>       return {
>         errMsg: '帳號和密碼請勿空白',
>         result: false
>       }
>     }
> 
>     // Here will call the login API
>     let {res, token} = await userAuth.login(para)
> 
>     if (res.result) {
>       commit('setUser', res.user)
>       commit('setAuthToken', token)
>       commit('setLoginTime', moment())
>       window.localStorage.setItem('AuthToken', token)
>     }
>     return res
>   }
> }
> ```
> 
> * Yap, it is related with vuex. It's is used to declare the entire web states and the method that can change the states.
> 
> [Vuex Reference](https://vuex.vuejs.org/guide/)

thx a lot for ur reply~ i have learnt about Vuex staff, but thx again for ur reply~
